### ISSUE TITLE
enums with a base type incorrectly indent

### ISSUE THREAD

**Issue by alexhairyman** [Emacs-D-Mode-Maintainers/Emacs-D-Mode#19]
I don't know if this is a ccmode indentation I can change, but here's what goes wrong:

``` D
enum GCode_Command : string // set the base type to be string
{
  RLM = "G00", // this one indents correctly 
    FRM = "G01", // this doesn't 
    OFFR = "G42" // ditto for this one
}
```

in addition, there is no highlighting done for the enum members

**Comment by johbo** [comment]
I am seeing sililar issues:

```d
enum MyValues {
    a,
    b,
    c
}


enum OtherValues {
    a = 2,
    b = 4,
    c
}


enum OtherValues2 : uint {
    a = 2u,
        b = 4u,
        c
        }
```
Seems it is recognized as a different thing. In the first two cases hitting `C-c C-s` tells me that it is a `brace-list-entry`, in the last case it tells me that it is a `statement-cont`. (tried the second entry of each)

I am not too familiar with cc-mode / d-mode yet unfortunately, but maybe it is "just" a matter of configuring it so that it recognizes both as the same thing or of adjusting my style configuration, so that in both cases the result is the same?

**Comment by arzoriac** [comment]
Is there any update or workaround on this?

**Comment by nordlow** [comment]
Further, the syntax coloring of enumerators gets ruined for me aswell

```
enum OtherValues2 : uint {
    a = 2u,
        b = 4u,
        c
        }
```

...
