### ISSUE TITLE
Occasional incorrect fontification of string literals due to escapes

### ISSUE THREAD

**Issue by nordlow** [Emacs-D-Mode-Maintainers/Emacs-D-Mode#49]
Fontification of string literals, for instance, in module `std.net.isemail.d` at line 907 on (git master) fails for me.

The line contains

``` D
    assert("\"test\\\u0000\"@iana.org".isEmail(CheckDns.no, EmailStatusCode.any).statusCode ==
        EmailStatusCode.deprecatedQuotedPair);
```

Another failure starts at line 1699 

`````` D
        backslash = `\`,
        dot = ".",
        doubleQuote = `"`,
```.
``````

**Comment by dmakarov** [comment]
It's not a work-around, but an observation -- if you delete the line 907 and then undo the delete, the line is fontified correctly after that. The same for the other incorrectly fontified lines in the file. Emacs is generally very slow when it fontifies the buffer with this file.  So it looks like an issue with some inefficiency caused by d-mode.

**Comment by MartinNowak** [comment]
Here is a reproducer, seems like the `\`` handling is countering the `\"` handling.
```d
`beg`
"\"bugbugbug"
`end`
```
