### ISSUE TITLE
if template constraints aren't indented correctly

### ISSUE THREAD

**Issue by tmccombs** [Emacs-D-Mode-Maintainers/Emacs-D-Mode#67]
If you have templates contstrainst on the second line of a template or function template definition, it is indented an extra level. For Example:

``` d
void foo(T)(T stuff)
    if (isInputRange!T) {
```

 instead of:

``` d
void foo(T)(T stuff)
if (isInputRange!T) {
```

no indentation for the continued line seems to be the norm in most D code I have seen.

**Comment by russel** [comment]
I am wondering if the best way forward here is to remove as much manually specified formatting as possible from the ELisp code of this mode and significantly improve the integration of DCD, Dfmt, Dfix, and Dscanner. Then the formatting in Emacs can be aligned to the tools used in Git, command line, etc. The idea here is to auto-generate the Emacs style rather than have it manually specified.
