### ISSUE TITLE
both `minimap-mode` and `sublimity-mode` don't work in `d-mode`

### ISSUE THREAD

**Issue by sprig** [Emacs-D-Mode-Maintainers/Emacs-D-Mode#86]
Hello,

As above. Using versions:
`sublimity-20170820.827` from `ELPA`.
`d-mode-20180215.727` from `ELPA`
`minimap-1.2` from `GNU`
`GNU Emacs 25.3.1 (x86_64-apple-darwin17.4.0, Carbon Version 158 AppKit 1561.2) of 2018-03-01
` from homebrew (package `emacs-mac`)
OSX 10.13.3

This also happens if I load emacs with `-Q`, load the `minimap` and `d-mode` packages and open any random file in D-mode (vs in another mode, such as built in `python-mode`). I was only able to verify with `minimap`, since `sublimity` does not appear to work in other modes either if I just load it - will make another attempt when time permits.

**Comment by CyberShadow** [comment]
`sublimity` didn't work for me at all. `minimap` wasn't considering `d-mode` as a descendant of `prog-mode` due to some old compatibility shim with very old Emacs versions, thus didn't activate (though it was possible to configure `minimap` to enable for `d-mode` as well.

Anyway, we didn't have any reasons to keep compatibility with old Emacs versions, and this issue is one reason to remove it, so I did; should work with `minimap` ouf-of-the-box now.

**Comment by sprig** [comment]
Thanks!

It works for me now with both sublimity and minimap...
If you care at all, this is how `sublimity` is setup on my end:

```
  ;; Load sublimity
  (use-package sublimity-map
    :bind ("C-`" . kk/toggle-sublimity)
    :init
    (setq sublimity-handle-scroll-criteria '((progn nil)))
    (setq sublimity-map-size 40)
    :config
    (sublimity-map-set-delay 0.1)

    (lexical-let ((sublimity-truncate-lines truncate-lines))
      (defun kk/toggle-sublimity ()
        (interactive)
        (message "%s" sublimity-truncate-lines)
        (if sublimity-mode
            (progn
              (setq truncate-lines sublimity-truncate-lines)
              (sublimity-mode 0)
              )
          (setq truncate-lines t)
          (sublimity-mode 1)
          (sublimity-map-show)
          )))
    )
(provide 'kk-sublimity)
```
