### ISSUE TITLE
Please do not bundle undercover

### ISSUE THREAD

**Issue by tarsius** [Emacs-D-Mode-Maintainers/Emacs-D-Mode#99]
If at all possible, then a repository used to maintain an Emacs package should not bundle any third-party libraries.

Bundling external dependencies might not cause any issues for users who install the package from Melpa, because packages distributed there can filter out unwanted libraries. But some people (including myself) run packages directly from their repositories (e.g. because that makes it much easier to contribute).

For such users the bundled library may end up on the `load-path`, possibly before the independently installed upstream version.  As a result some outdated version can end up being loaded and that can be very confusing and hard to debug.

I recommend that you never bundle any third-party libraries.  If that is not possible, then I recommend that you put those libraries in a separate directory and alongside a file named `.nosearch`. The existence of this file instructs some tools (such as `normal-top-level-add-subdirs-to-load-path`, my [`borg`](https://emacsair.me/2016/05/17/assimilate-emacs-packages-as-git-submodules/) package manager, and the tools I use to maintain the Emacsmirror) to ignore the containing directory.

Thanks for considering this!

<sub>I have written similar messages many many times so I now [use a template](https://help.github.com/en/github/writing-on-github/working-with-saved-replies). I try to adjust it to match each individual case but it might still not apply 100% in all cases.</sub>

**Comment by CyberShadow** [comment]
At the time, Undercover was bundled because it contained some fixes necessary for this repository. Since then, the previous undercover maintainer handed oversight of the project to me and I upstreamed all of these fixes, so we can stop bundling a custom Undercover variant now.

That said - the file is already in a subdirectory (and only loaded when running the test suite), and it seems very troubling to me that there exists software that will load code from arbitrarily nested directories. That seems like a security catastrophe waiting to happen.

Do we also need to worry about other .el files, such as test runners or tests?

**Comment by tarsius** [comment]
> it seems very troubling to me that there exists software that will load code from arbitrarily nested directories.

Borg doesn't actually do that. I will remove that part from the message template.

But the tools that are used to maintain the Emacsmirror will continue to look in all directories.

> Do we also need to worry about other .el files, such as test runners or tests?

If those files are located in the same directories as the actual libraries then yes, because those directories need to be on the `load-path`.
